security:

    encoders:
        App\Entity\User:
            algorithm: auto
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        users_in_memory: { memory: null }

        in_database:
            entity:
                class: App\Entity\User
                property: abonne_email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true

            provider: in_database

            form_login:
                login_path: security_login
                check_path: security_login
                
            logout:
                path: security_logout
                target: accueil

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profil, roles: ROLE_USER }
        - { path: ^/blog, roles: ROLE_USER }
        - { path: ^/chat, roles: ROLE_USER }
        # - { path: ^/login, roles: ROLE_USER }

    access_denied_url: blog